from curses.ascii import SO


NORTHBOUND_DEPARTING_BLOCKS = [
    # ("Forest Park", "wc461t"),
    ("Harlem (Forest Park Branch)", "wc437t"),
    ("Oak Park", "wc395t"),
    ("Austin", "wc355t"),
    ("Cicero", "wc273t"),
    ("Pulaski", "wc219t"),
    ("Kedzie-Homan", "wc166t"),
    ("Western (Forest Park Branch)", "wc111t"),
    ("Illinois Medical District", "wc069t"),
    ("Racine", "wc032t"),
    ("UIC-Halsted", "wc005t"),
    ("Clinton", "dc017t"),
    ("LaSalle", "dc040"),
    ("Jackson", "dc059t"),
    ("Monroe", "dc070t"),
    ("Washington", "dc080t"),
    ("Clark/Lake", "dc093t"),
    ("Grand", "dc143t"),
    ("Chicago", "dc169t"),
    ("Division", "dc213t"),
    ("Damen", "ln1238t"),
    ("Western (O-Hare Branch)", "ln1271t"),
    ("California", "ln1306"),
    ("Logan Square", "nwc114t"),
    ("Belmont", "nwc149t"),
    ("Addison", "nwc187t"),
    ("Irving Park", "nwc221t"),
    ("Montrose", "nwc273t"),
    ("Jefferson Park", "nwc330t"),
    ("Harlem (O-Hare Branch)", "nwc475t"),
    ("Cumberland", "nwc555t"),
    ("Rosemont", "nwc610"),
]

SOUTHBOUND_DEPARTING_BLOCKS = [
    # ("O-Hare", "nwd727t"),
    ("Rosemont", "nwd606t"),
    ("Cumberland", "nwd547t"),
    ("Harlem (O-Hare Branch)", "nwd468t"),
    ("Jefferson Park", "nwd325t"),
    ("Montrose", "nwd267t"),
    ("Irving Park", "nwd215t"),
    ("Addison", "nwd182t"),
    ("Belmont", "nwd143t"),
    ("Logan Square", "nwd107t"),
    ("California", "ln2301t"),
    ("Western (O-Hare Branch)", "ln2266t"),
    ("Damen", "ln2233"),
    ("Division", "dd208t"),
    ("Chicago", "dd164t"),
    ("Grand", "dd138t"),
    ("Clark/Lake", "dd088t"),
    ("Washington", "dd072t"),
    ("Monroe", "dd063t"),
    ("Jackson", "dd054t"),
    ("LaSalle", "dd035t"),
    ("Clinton", "dd012t"),
    ("UIC-Halsted", "wd011t"),
    ("Racine", "wd040"),
    ("Illinois Medical District", "wd075t"),
    ("Western (Forest Park Branch)", "wd117t"),
    ("Kedzie-Homan", "wd172t"),
    ("Pulaski", "wd225t"),
    ("Cicero", "wd279t"),
    ("Austin", "wd361t"),
    ("Oak Park", "wd401t"),
    ("Harlem (Forest Park Branch)", "wd444t"),
    # ("Forest Park", "wd452t"),
]
